### ISSUE TITLE
[BUG] when user assign a group to a dataset, report the Internal Error.

### ISSUE THREAD

**Issue by Mukvin** [Kyligence/mdx-kylin#8]
**Describe the bug**
Assign a group to a dataset throws error:
```
[MDX-00000001] Internal Error, com.alibaba.fastjson.JSONArray cannot be cast to com.alibaba.fastjson.JSONObject
java.lang.ClassCastException: com.alibaba.fastjson.JSONArray cannot be cast to com.alibaba.fastjson.JSONObject
 at com.alibaba.fastjson.JSONObject.getJSONObject(JSONObject.java:140)
 at io.kylin.mdx.insight.core.meta.acl.KylinAclConvertor.hasTablePermissionByGroup(KylinAclConvertor.java:125)
 at io.kylin.mdx.insight.core.meta.acl.KylinAclConvertor.generateAclByGroup(KylinAclConvertor.java:69)
 at io.kylin.mdx.insight.core.meta.acl.KylinAclConvertor.getAclProjectModel(KylinAclConvertor.java:57)
 at io.kylin.mdx.insight.core.meta.KylinConvertor.getAclProjectModel(KylinConvertor.java:539)
 at io.kylin.mdx.insight.core.meta.SemanticAdapter.getAclModel(SemanticAdapter.java:155)
 at io.kylin.mdx.insight.server.facade.AclFacade.preparePermission(AclFacade.java:53)
 at io.kylin.mdx.insight.server.controller.AclController.getAcl(AclController.java:62)
 at io.kylin.mdx.insight.server.controller.AclController$$FastClassBySpringCGLIB$$812005c9.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
...

```

**Expected behavior**
add group successfully without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/34978943/173823384-87e586b1-43b5-4158-b17a-d86690e3beda.png)
![image](https://user-images.githubusercontent.com/34978943/173823405-cc62bcb7-4df2-4efc-a896-29f5698e369b.png)
![image](https://user-images.githubusercontent.com/34978943/173823414-9a985e6d-3770-43d5-be05-284df61d631f.png)
![image](https://user-images.githubusercontent.com/34978943/173823422-d0e03e57-82fc-44dc-909e-bf897a4cc6b4.png)
**Additional context**

**Comment by Mukvin** [comment]
# root cause
io/kylin/mdx/insight/core/meta/acl/KylinAclConvertor.java:125

result.getJSONObject("data") can not be cast.
```
      JSONArray groupList = result.getJSONObject("data").getJSONArray("group");
```

need to change to as followed:
```
    JSONArray groupList = result.getJSONArray("data");
```

**Comment by Mukvin** [comment]
# Solution

replace the [jar](https://s3.cn-north-1.amazonaws.com.cn/public.kyligence.io/kylin/jars/semantic-service.jar) in $MDX_HOME/semantic-mdx/semantic-service.jar
